openapi: 3.0.0
info:
  title: ultimate.bot
  version: 0.0.1

servers:
  - url: http://127.0.0.1:8000


paths:
  /reply:
    post:
      summary: Get a text reply for a message.
      parameters:
        - in: query
          name: replyConfidence
          schema:
            type: number
      requestBody:
        description: contains bot identifier and message
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VisitorMessage'
      responses:
        '200':
          description: Contains text response
          content:
            'application/json; charset=utf-8':
              schema:
                $ref: '#/components/schemas/Reply'
        '400':
          $ref: '#/components/responses/BadRequestError'
        '500':
          $ref: '#/components/responses/InternalError'
 
components:

  # RESPONSES
  responses:
    ## ERRORS
    InternalError:
      description: internal error
      content:
        'application/json; charset=utf-8':
          schema:
            type: object
            required:
              - message
            properties:
              message:
                type: string
                example: 'internal error'

    BadRequestError:
      description: Invalid operation params
      content:
        'application/json; charset=utf-8':
          schema:
            type: object
            required:
              - message
            properties:
              message:
                type: string
                example: 'bad request'
  # SCHEMAS
  schemas:
    Reply:
      type: object
      required:
        - text
      properties:
        text:
          description: 'Bot Reply'
          type: string
          example: 'Hello!'
    VisitorMessage:
      type: object
      required:
        - bot_id
        - visitor_message
      properties:
        bot_id:
          description: 'Bot Identifier'
          type: string
          example: '5f74865056d7bb000fcd39ff'
        visitor_message:
          description: 'Typed user message'
          type: string
          example: 'Knock Knock'
  